company: Strategic AI Solutions
legal_name: "Alexander Kolodzig EI"
my_name_en: "Alex Kolodzig"
my_name_de: "Dr. Alex Kolodzig"
my_role_en: "Freelance Data Scientist & AI Engineer"
my_role_de: "freiberuflicher Data Scientist & KI Ingenieur"
meeting_link: https://zcal.co/strategic-ai/30min-meeting
logo: https://strategic-ai.eu/logo.svg
favicon: https://strategic-ai.eu/company_logo_02_bw_reverse_noedge_512.png
profile_image: https://strategic-ai.eu/20240705_blue_bkg_0063FB_border_300.png
image_url: https://strategic-ai.eu/assets/ia_images/
url_legal: https://www.strategic-ai.eu/legal_notice/legal_notice_v7.html
n_exp_years: 8
font_family: "Dosis Light"
baseurl: "/strategic-ai"
exclude: ["README.md", ".markdownlint.json", "LICENSE"]
lang: en
