title: title
description: description
company: Strategic AI Solutions
pitch: Your partner in predictive maintenance and cutting edge AI, delivering robust, real world systems.
legal_name: [My Full Name] EI
my_name: [My Full Name]
my_role: Freelance Data Scientist & AI Engineer
meeting_link: https://zcal.co/strategic-ai/30min-meeting