company: Strategic AI Solutions
legal_name: "Alexander Kolodzig EI"
my_name:
  en: "Alex Kolodzig"
  de: "Dr. Alex Kolodzig"
my_role:
  en: "Freelance Data Scientist & AI Engineer"
  de: "freiberuflicher Data Scientist & KI Ingenieur"
meeting_link: https://zcal.co/strategic-ai/30min-meeting
profile_image: https://strategic-ai.eu/20240705_blue_bkg_0063FB_border_300.png
url_ai_images: https://strategic-ai.eu/assets/ia_images/
url_legal: https://strategic-ai.eu/legal_notice/legal_notice_v7.html
n_exp_years: 8
font_family: "Dosis Light"
baseurl: "/strategic-ai"
exclude: ["README.md", ".markdownlint.json", "LICENSE"]
lang: en
